# Generated by Django 2.2.5 on 2021-03-24 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_writer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'default_related_name': 'posts'},
        ),
    ]
