# Generated by Django 2.2.5 on 2021-04-04 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20210330_0123'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='hits',
            field=models.IntegerField(default=0),
        ),
    ]
