# Generated by Django 2.2.5 on 2021-02-07 05:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Community',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True, validators=[django.core.validators.RegexValidator(message='Only alphanumeric characters are allowed', regex='^[0-9a-zA-Z]*$')])),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('avatar', models.ImageField(null=True, upload_to='avatar/communities/')),
                ('photo', models.ImageField(null=True, upload_to='photos/communities/')),
            ],
        ),
    ]
