# Generated by Django 2.2.5 on 2021-03-30 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0002_community_creater'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatar/communities/'),
        ),
        migrations.AlterField(
            model_name='community',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='photos/communities/'),
        ),
    ]
