# Generated by Django 2.2.5 on 2021-02-21 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0003_auto_20210215_1229'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='title',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
